name: 'dbt_project'
version: '1.0.0'
config-version: 2

profile: 'sqlserver'

model-paths: ["models"]

models:
  dbt_project:
    +materialized: table

    bronze:
      +schema: bronze

    silver:
      +schema: silver

    gold:
      +schema: gold








