name: 'dbt_project'
version: '1.0.0'
config-version: 2

profile: 'sqlserver'

model-paths: ["models"]

models:
  +materialized: table  

  gold:  
    +materialized: view  # sobrescreve para os modelos da pasta gold






