sqlserver:
  outputs:
    dev:
      type: sqlserver
      driver: "ODBC Driver 18 for SQL Server"
      server: "ALEXSANDER,1433"
      database: "master"  # Troque pelo nome correto do seu banco de dados
      schema: "dbo"
      windows_login: True
      encrypt: True
      trust_cert: True
  target: dev


