version: 2

sources:
  - name: default
    database: dbt_project_catalog
    schema: default
    tables:
      - name: orders
        columns:
          - name: id
            tests:
              - not_null
        loaded_at_field: created_at
        freshness:
          warn_after:
            count: 365
            period: day

      - name: products

      - name: reviews

      - name: users


      


